title: BTech FY
description: Resources and reference materials for first-year BTech, including assignments and notes.
theme: jekyll-theme-cayman
show_downloads: true
github:
  another_url: http://example.com/download.zip
